In [1]:
import numpy as np

v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
print("Vector 1:", v1)
print("Vector 2:", v2)

Vector 1: [1 2 3]
Vector 2: [4 5 6]


In [2]:
v_add = v1+v2
v_sub = v1-v2
print(v_add, v_sub)

[5 7 9] [-3 -3 -3]


In [3]:
v_scale = v1 * 5
print(v_scale)

[ 5 10 15]


In [8]:
v_mult = v1*v2
v_dot = np.dot(v1,v2)
print(v_mult)
print(v_dot)

[ 4 10 18]
32


In [9]:
magnitude = np.linalg.norm(v1)
print(magnitude)

3.7416573867739413


In [12]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
print()
print(B)

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
C = np.array([[1,2,3],[4,5,6]])
# matrix must be the SAME size to add / subtract
matrix_add = A+C
matrix_subtract = A-C
print(matrix_add)
print()
print(matrix_subtract)

[[ 2  4  6]
 [ 8 10 12]]

[[0 0 0]
 [0 0 0]]


In [15]:
matrix_mult = np.dot(A,B)
#1st row * 1st column ...
print(matrix_mult)

[[30 36 42]
 [66 81 96]]


In [16]:
transpose_A = A.T
print(transpose_A)

[[1 4]
 [2 5]
 [3 6]]


In [17]:
#2x+4y = 5
#3x-y = 3
A = np.array([[2,3], [4,-1]])
b = np.array([5,3])
x = np.linalg.solve(A,b)
print(x)
#[x , y]

[1. 1.]


Av = lambda * v

Eigenvectors (v) are directions that don't change direction when a matrix acts on them,
Eigenvalues (lambda) tell you how much those directions get stretched or squished
    - negative = system decaying , postive = system growth , complex = oscillations

Eigenvectors = directions of max variance,
Eigenvalues = how important each direction is

Eigenvectors = natural vibrations modes,
Eigenvalues = frequencies

In [18]:
A = np.array([[2,1],[1,2]])
eigenvalues, eigenvectors = np.linalg.eig(A)

In [19]:
print(eigenvalues)
print(eigenvectors)

[3. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [20]:
A = np.array([[4,7],[2,6]])
A_inv = np.linalg.inv(A)
print(A)
print()
print(A_inv)

[[4 7]
 [2 6]]

[[ 0.6 -0.7]
 [-0.2  0.4]]


In [21]:
identity = np.dot(A, A_inv)
print(identity)

[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


1 0 0     idea of an identity matrix
0 1 0
0 0 1

In [23]:
A = np.array([[1,2],[3,4],[5,6]])
U, sigma, Vt = np.linalg.svd(A)
print(U)
print()
print(sigma)
print()
print(Vt)

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

[9.52551809 0.51430058]

[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
